# Generated by Django 4.2 on 2026-02-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fhir_practitioner_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
