# Generated by Django 4.2 on 2026-02-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0002_doctor_fhir_practitioner_id'),
        ('doctor_app', '0002_initial'),
    ]

    operations = [
    ]
