# Generated by Django 5.2.9 on 2026-01-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='user',
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
