# Generated by Django 4.2 on 2026-02-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_alter_laboratory_name'),
        ('laboratory', '0002_remove_laboratory_user_alter_laboratory_address_and_more'),
    ]

    operations = [
    ]
