# Generated by Django 4.2 on 2026-01-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0002_remove_hospital_address_remove_hospital_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
