# Generated by Django 4.2 on 2026-02-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0003_alter_hospital_city_alter_hospital_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='registration_id',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='state',
        ),
        migrations.AddField(
            model_name='hospital',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
