# Generated by Django 4.2 on 2026-01-17 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientaccess',
            name='created_at',
        ),
    ]
