# Generated by Django 4.2 on 2026-01-29 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0001_initial'),
        ('patients', '0003_appointment_created_at_alter_appointment_doctor_and_more'),
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientaccess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patientaccess',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='doctor_app.doctor'),
        ),
        migrations.AlterField(
            model_name='patientaccess',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='patients.patient'),
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
    ]
