# Generated by Django 4.2 on 2026-01-17 14:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0001_initial'),
        ('patients', '0003_appointment_created_at_alter_appointment_doctor_and_more'),
        ('access_control', '0002_remove_patientaccess_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientaccess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientaccess',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_accesses', to='doctor_app.doctor'),
        ),
        migrations.AlterField(
            model_name='patientaccess',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='patients.patient'),
        ),
    ]
