# Generated by Django 4.2 on 2026-02-12 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0004_remove_hospital_city_remove_hospital_registration_id_and_more'),
        ('access_control', '0003_patientaccess_from_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientaccess',
            name='from_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_requests', to='hospital_app.hospital'),
        ),
        migrations.AlterField(
            model_name='patientaccess',
            name='to_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_requests', to='hospital_app.hospital'),
        ),
    ]
