# Generated by Django 4.2 on 2026-01-21 17:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0001_initial'),
        ('patients', '0003_appointment_created_at_alter_appointment_doctor_and_more'),
        ('access_control', '0003_patientaccess_created_at_alter_patientaccess_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientaccess',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='patientaccess',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.doctor'),
        ),
        migrations.AlterField(
            model_name='patientaccess',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
