# Generated by Django 4.2 on 2026-02-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_alter_patientaccess_created_at_and_more'),
        ('access_control', '0004_alter_patientaccess_from_hospital_and_more'),
        ('access_control', '0005_observation'),
    ]

    operations = [
    ]
