# Generated by Django 4.2 on 2026-01-15 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_remove_laboratory_user_alter_laboratory_address_and_more'),
        ('records', '0001_initial'),
    ]

    operations = [
        #migrations.RemoveField(
         #   model_name='report',
          #  name='doctor_notes',
        #),
        migrations.AddField(
            model_name='report',
            name='doctor_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='explained_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.laboratory'),
        ),
    ]
