# Generated by Django 4.2 on 2025-12-29 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='doctor_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.laboratory'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
