# Generated by Django 4.2 on 2026-01-25 15:51

from django.db import migrations, models
from django.utils import timezone
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0001_initial'),
        ('patients', '0003_appointment_created_at_alter_appointment_doctor_and_more'),
        ('hospital_app', '0003_alter_hospital_city_alter_hospital_state'),
        ('records', '0002_encounter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='date',
        ),
        migrations.AddField(
            model_name='encounter',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='reason',
            field=models.CharField(default='Initial consultation', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encounter',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encounter',
            name='status',
            field=models.CharField(choices=[('in-progress', 'In Progress'), ('finished', 'Finished')], default='in-progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='doctor_app.doctor'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='hospital_app.hospital'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='patients.patient'),
        ),
    ]
