# Generated by Django 4.2 on 2026-01-15 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_remove_laboratory_user_alter_laboratory_address_and_more'),
        ('records', '0002_remove_report_doctor_notes_report_doctor_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='doctor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='laboratory.laboratory'),
        ),
    ]
