# Generated by Django 4.2 on 2026-02-15 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_fhir_patient_id'),
        ('hospital_app', '0005_remove_hospital_address_and_more'),
        ('doctor_app', '0002_doctor_fhir_practitioner_id'),
        ('records', '0003_prescription_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.doctor'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='encounter',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='records.encounter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital_app.hospital'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
