# Generated by Django 4.2 on 2026-01-17 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_report_doctor_notes_alter_report_laboratory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='doctor_explanation',
        ),
        migrations.RemoveField(
            model_name='report',
            name='explained_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='status',
        ),
    ]
