# Generated by Django 4.2 on 2026-01-26 15:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0001_initial'),
        ('records', '0003_remove_encounter_date_encounter_ended_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='status',
        ),
        migrations.AlterField(
            model_name='encounter',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='doctor_app.doctor'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='reason',
            field=models.CharField(help_text='Reason for visit (FHIR: reasonCode)', max_length=255),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
