# Generated by Django 4.2 on 2026-02-15 08:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0005_remove_hospital_address_and_more'),
        ('doctor_app', '0002_doctor_fhir_practitioner_id'),
        ('patients', '0005_patient_fhir_patient_id'),
        ('records', '0004_prescription_patient_alter_prescription_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='doctor_app.doctor'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='records.encounter'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='hospital_app.hospital'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
