# Generated by Django 4.2 on 2026-01-26 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0001_initial'),
        ('records', '0004_remove_encounter_status_alter_encounter_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='FHIR Observation code (e.g. BP, TEMP, HB)', max_length=100)),
                ('value', models.CharField(help_text='Observed value', max_length=100)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor_app.doctor')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='records.encounter')),
            ],
        ),
    ]
