# Generated by Django 4.2 on 2026-01-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_report_file_alter_observation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
