# Generated by Django 4.2 on 2026-02-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_initial'),
        ('records', '0002_remove_prescription_patient_and_more'),
        ('records', '0002_report_doctor_notes_report_laboratory_and_more'),
        ('records', '0005_dummy_fix'),
        ('records', '0005_observation'),
        ('records', '0005_report_uploaded_at_alter_prescription_doctor_and_more'),
        ('records', '0010_alter_encounter_reason_alter_observation_doctor_and_more'),
    ]

    operations = [
    ]
