# Generated by Django 4.2 on 2025-12-26 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='file',
        ),
        migrations.AddField(
            model_name='report',
            name='report_pdf',
            field=models.FileField(blank=True, null=True, upload_to='reports/pdfs/'),
        ),
        migrations.AddField(
            model_name='report',
            name='scan_image',
            field=models.ImageField(blank=True, null=True, upload_to='reports/images/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
