# Generated by Django 4.2 on 2025-12-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='patient_reports/'),
        ),
    ]
