# Generated by Django 4.2 on 2026-02-12 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0004_remove_hospital_city_remove_hospital_registration_id_and_more'),
        ('patients', '0003_appointment_created_at_alter_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_app.hospital'),
        ),
    ]
