# Generated by Django 4.2 on 2026-02-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_report_file_report_report_pdf_and_more'),
        ('patients', '0003_doctor_remove_patient_age_remove_patient_name_and_more'),
        ('patients', '0005_patient_fhir_patient_id'),
    ]

    operations = [
    ]
